# Generated by Django 4.1.1 on 2022-09-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localise', '0003_counties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='dis',
            field=models.IntegerField(null=True),
        ),
    ]
