# Generated by Django 4.1.1 on 2022-09-13 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localise', '0004_alter_counties_dis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counties',
            options={'verbose_name_plural': ' Counties'},
        ),
    ]
